name: Patch Image via URL

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'Coloque a URL Direta da sua imagem aqui'
        default: 'https://files.catbox.moe/17m8e6.img'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
    - name: Gain file access
      uses: actions/checkout@v4.1.1
    
    - name: Fetch necessary packages
      run: |
         sudo apt install git wget lz4 tar openssl python3 -y
         
    - name: Download Recovery Image
      run: |
        curl -fLo recovery.img "${{ github.event.inputs.image_url }}"

    - name: Start patching script
      run: |
         curl -fLo magisk.zip https://github.com/topjohnwu/Magisk/releases/download/v27.0/Magisk-v27.0.apk
         unzip -j magisk.zip "lib/x86_64/libmagiskboot.so" -d .
         mv libmagiskboot.so magiskboot
         chmod a+x magiskboot
         chmod a+x patcher-minimal

         sed -i 's/count=$off/count=${off:-$(stat -c%s raw.img)}/g' patcher-minimal

         bash -x ./patcher-minimal
        
    - name: Upload Patched Image and Keys
      uses: actions/upload-artifact@v4
      with:
        name: Magisk-Patched-Recovery-Bundle
        path: |
          *.img
          *.tar
          *.tar.md5
          keys/
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true
